import argparse
import difflib
import json
from pathlib import Path

import streamlit as st


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Loop optimizer visualization dashboard")
    parser.add_argument("--input", required=True, help="Path to original source file")
    parser.add_argument("--output", required=True, help="Path to optimized source file")
    parser.add_argument("--metrics", default="", help="Optional metrics json file generated by runner")
    return parser.parse_args()


def safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def count_changed_lines(before: str, after: str) -> tuple[int, int, int]:
    before_lines = before.splitlines()
    after_lines = after.splitlines()

    added = 0
    removed = 0
    for line in difflib.ndiff(before_lines, after_lines):
        if line.startswith("+ "):
            added += 1
        elif line.startswith("- "):
            removed += 1

    changed = min(added, removed)
    return added, removed, changed


def load_metrics(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except json.JSONDecodeError:
        return {}


def render_code_columns(input_name: str, output_name: str, src_before: str, src_after: str) -> None:
    left, right = st.columns(2)

    with left:
        st.subheader(f"Original: {input_name}")
        st.code(src_before or "File is empty or missing.", language="c")

    with right:
        st.subheader(f"Optimized: {output_name}")
        st.code(src_after or "File is empty or missing.", language="c")


def render_diff(src_before: str, src_after: str, input_name: str, output_name: str) -> None:
    diff = difflib.unified_diff(
        src_before.splitlines(),
        src_after.splitlines(),
        fromfile=input_name,
        tofile=output_name,
        lineterm="",
    )
    diff_text = "\n".join(diff)
    with st.expander("Unified diff", expanded=False):
        st.code(diff_text if diff_text else "No textual difference found.", language="diff")


def render_metrics_card(metrics: dict, src_before: str, src_after: str) -> None:
    added, removed, changed = count_changed_lines(src_before, src_after)

    input_lines = len(src_before.splitlines())
    output_lines = len(src_after.splitlines())

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Input lines", input_lines)
    col2.metric("Output lines", output_lines, delta=output_lines - input_lines)
    col3.metric("Added lines", added)
    col4.metric("Removed lines", removed)

    st.caption(f"Approx changed-line overlap: {changed}")

    improvement = metrics.get("timing", {}).get("improvement_percent")
    if improvement is not None:
        tcol1, tcol2, tcol3 = st.columns(3)
        tcol1.metric("Original time (s)", f"{metrics['timing'].get('original_seconds', 0.0):.6f}")
        tcol2.metric("Optimized time (s)", f"{metrics['timing'].get('optimized_seconds', 0.0):.6f}")
        tcol3.metric("Improvement %", f"{improvement:.2f}%")


def render_optimizer_output(metrics: dict) -> None:
    stdout = metrics.get("stdout", "").strip()
    stderr = metrics.get("stderr", "").strip()

    if not stdout and not stderr:
        return

    st.subheader("Optimizer output")
    if stdout:
        st.code(stdout, language="text")
    if stderr:
        with st.expander("stderr", expanded=False):
            st.code(stderr, language="text")


def main() -> None:
    args = parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)
    metrics_path = Path(args.metrics) if args.metrics else Path("")

    src_before = safe_read(input_path)
    src_after = safe_read(output_path)
    metrics = load_metrics(metrics_path) if args.metrics else {}

    st.set_page_config(page_title="Loop Optimizer Visual Compare", layout="wide")
    st.title("Loop Optimizer Visual Comparison")
    
    render_metrics_card(metrics, src_before, src_after)
    render_optimizer_output(metrics)
    render_code_columns(input_path.name, output_path.name, src_before, src_after)
    render_diff(src_before, src_after, input_path.name, output_path.name)


if __name__ == "__main__":
    main()
