import argparse
import difflib
import json
import subprocess
from datetime import datetime
from pathlib import Path

import streamlit as st


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Loop Optimizer Dashboard")
    parser.add_argument("--input", default="", help="Optional path to original source file")
    parser.add_argument("--output", default="", help="Optional path to optimized source file")
    parser.add_argument("--metrics", default="", help="Optional metrics json file generated by runner")
    parser.add_argument("--optimizer", default="", help="Optional path to optimizer executable")
    return parser.parse_args()


def safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def count_changed_lines(before: str, after: str) -> tuple[int, int, int]:
    before_lines = before.splitlines()
    after_lines = after.splitlines()

    added = 0
    removed = 0
    for line in difflib.ndiff(before_lines, after_lines):
        if line.startswith("+ "):
            added += 1
        elif line.startswith("- "):
            removed += 1

    changed = min(added, removed)
    return added, removed, changed


def load_metrics(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except json.JSONDecodeError:
        return {}


def detect_optimizer(explicit: str, workspace: Path) -> Path | None:
    if explicit:
        candidate = Path(explicit)
        if candidate.exists():
            return candidate
        return None

    for name in ("loop_optimizer.exe", "loop_optimizer_split.exe"):
        candidate = workspace / name
        if candidate.exists():
            return candidate
    return None


def run_backend_optimization(upload_name: str, source_text: str, optimizer: Path, workspace: Path) -> dict:
    runs_dir = workspace / "dashboard_runs"
    runs_dir.mkdir(parents=True, exist_ok=True)

    safe_name = Path(upload_name).name
    suffix = Path(safe_name).suffix or ".c"
    stem = Path(safe_name).stem or "input"
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    input_path = runs_dir / f"{stem}_{ts}{suffix}"
    output_path = runs_dir / f"{stem}_{ts}_optimized{suffix}"
    report_json = runs_dir / f"{stem}_{ts}_report.json"

    input_path.write_text(source_text, encoding="utf-8")

    cmd = [
        str(optimizer),
        str(input_path),
        "--output",
        str(output_path),
        "--report-json",
        str(report_json),
        "--no-compare",
    ]
    run = subprocess.run(cmd, cwd=workspace, capture_output=True, text=True)

    metrics = {
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "optimizer": str(optimizer.name),
        "input": str(input_path),
        "output": str(output_path),
        "return_code": run.returncode,
        "stdout": run.stdout,
        "stderr": run.stderr,
    }

    if report_json.exists():
        metrics["optimizer_report"] = load_metrics(report_json)

    return {
        "input_path": input_path,
        "output_path": output_path,
        "metrics": metrics,
        "ok": run.returncode == 0 and output_path.exists(),
    }


def render_code_columns(input_name: str, output_name: str, src_before: str, src_after: str) -> None:
    left, right = st.columns(2)

    with left:
        st.subheader(f"Original: {input_name}")
        st.code(src_before or "File is empty or missing.", language="c")

    with right:
        st.subheader(f"Optimized: {output_name}")
        st.code(src_after or "File is empty or missing.", language="c")


def render_diff(src_before: str, src_after: str, input_name: str, output_name: str) -> None:
    diff = difflib.unified_diff(
        src_before.splitlines(),
        src_after.splitlines(),
        fromfile=input_name,
        tofile=output_name,
        lineterm="",
    )
    diff_text = "\n".join(diff)
    with st.expander("Unified diff", expanded=False):
        st.code(diff_text if diff_text else "No textual difference found.", language="diff")


def render_metrics_card(metrics: dict, src_before: str, src_after: str) -> None:
    added, removed, changed = count_changed_lines(src_before, src_after)

    input_lines = len(src_before.splitlines())
    output_lines = len(src_after.splitlines())

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Input lines", input_lines)
    col2.metric("Output lines", output_lines, delta=output_lines - input_lines)
    col3.metric("Added lines", added)
    col4.metric("Removed lines", removed)

    st.caption(f"Approx changed-line overlap: {changed}")

    improvement = metrics.get("timing", {}).get("improvement_percent")
    if improvement is not None:
        tcol1, tcol2, tcol3 = st.columns(3)
        tcol1.metric("Original time (s)", f"{metrics['timing'].get('original_seconds', 0.0):.6f}")
        tcol2.metric("Optimized time (s)", f"{metrics['timing'].get('optimized_seconds', 0.0):.6f}")
        tcol3.metric("Improvement %", f"{improvement:.2f}%")


def render_optimizer_output(metrics: dict) -> None:
    stdout = metrics.get("stdout", "").strip()
    stderr = metrics.get("stderr", "").strip()

    if not stdout and not stderr:
        return

    st.subheader("Optimizer output")
    if stdout:
        st.code(stdout, language="text")
    if stderr:
        with st.expander("stderr", expanded=False):
            st.code(stderr, language="text")


def render_optimizer_report(metrics: dict) -> None:
    report = metrics.get("optimizer_report", {})
    if not report:
        return

    st.subheader("Optimization counters")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Loops detected", report.get("loopsDetected", 0))
    c2.metric("Loops unrolled", report.get("loopsUnrolled", 0))
    c3.metric("Safety skips", report.get("loopsSkippedSafety", 0))
    c4.metric("Elapsed (ms)", report.get("elapsedMs", 0))


def main() -> None:
    args = parse_args()
    workspace = Path(__file__).resolve().parent

    st.set_page_config(page_title="Loop Optimizer Visual Compare", layout="wide")
    st.title("Loop Optimizer")

    optimizer = detect_optimizer(args.optimizer, workspace)

    if optimizer is None:
        st.error("Optimizer executable not found in workspace.")
        st.caption("Expected loop_optimizer.exe or loop_optimizer_split.exe")

    run_data = None

    if args.input and args.output:
        input_path = Path(args.input)
        output_path = Path(args.output)
        metrics_path = Path(args.metrics) if args.metrics else Path("")

        src_before = safe_read(input_path)
        src_after = safe_read(output_path)
        metrics = load_metrics(metrics_path) if args.metrics else {}
        run_data = {
            "input_path": input_path,
            "output_path": output_path,
            "src_before": src_before,
            "src_after": src_after,
            "metrics": metrics,
            "ok": True,
        }
    else:
        st.subheader(" Select Source File")
        uploaded = st.file_uploader(
            "Upload C/C++ source file",
            type=["c","cpp"],
            accept_multiple_files=False,
        )

        can_run = uploaded is not None and optimizer is not None
        if st.button("Optimize", type="primary", disabled=not can_run):
            src_before = uploaded.getvalue().decode("utf-8", errors="replace")
            result = run_backend_optimization(uploaded.name, src_before, optimizer, workspace)
            if result["ok"]:
                st.session_state["last_run"] = {
                    "input_path": result["input_path"],
                    "output_path": result["output_path"],
                    "src_before": src_before,
                    "src_after": safe_read(result["output_path"]),
                    "metrics": result["metrics"],
                    "ok": True,
                }
            else:
                st.session_state["last_run"] = {
                    "input_path": result["input_path"],
                    "output_path": result["output_path"],
                    "src_before": src_before,
                    "src_after": safe_read(result["output_path"]),
                    "metrics": result["metrics"],
                    "ok": False,
                }

        run_data = st.session_state.get("last_run")

    if not run_data:
        st.info("Upload a file, then click Optimize in backend.")
        return

    src_before = run_data["src_before"]
    src_after = run_data["src_after"]
    metrics = run_data["metrics"]
    input_path = run_data["input_path"]
    output_path = run_data["output_path"]

    st.subheader("Optimized File")
    if run_data.get("ok"):
        st.success("Optimization completed successfully.")
    else:
        st.error("Optimization failed. See optimizer output below.")

    render_metrics_card(metrics, src_before, src_after)
    render_optimizer_report(metrics)
    render_optimizer_output(metrics)
    render_code_columns(input_path.name, output_path.name, src_before, src_after)
    render_diff(src_before, src_after, input_path.name, output_path.name)

    st.download_button(
        label="Download optimized file",
        data=src_after,
        file_name=output_path.name,
        mime="text/plain",
        disabled=not bool(src_after.strip()),
    )


if __name__ == "__main__":
    main()
